### ISSUE TITLE
"ALT+U N" throws ClassCastException somewhere in ccw-plugin-manager/create-user-plugin

### ISSUE THREAD

**Issue by birdspider** [laurentpetit/ccw-plugin-manager#3]
Hello,

fresh eclipse-mars + ccw from MarketPlace; was attemting a new user plugin.

Should/how can I provide more info?

```
!ENTRY org.eclipse.ui 4 0 2015-08-03 12:11:25.432
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.lang.RuntimeException: Exception while executing code from bundle ccw.core
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1550)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1326)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1351)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1336)
        at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1363)
        at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:763)
        at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3317)
        at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:785)
        at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1965)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:5590)
        at org.eclipse.swt.widgets.Table.windowProc(Table.java:3699)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:4717)
        at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
        at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9272)
        at org.eclipse.swt.widgets.Display.eventProc(Display.java:1225)
        at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
        at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2422)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3428)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.RuntimeException: Exception while executing code from bundle ccw.core
        at ccw.util.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:112)
        at ccw.util.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:52)
        at ccw.util.GenericHandler.execute(GenericHandler.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
        ... 54 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.concurrent.Future
        at clojure.core$deref_future.invoke(core.clj:2184)
        at clojure.core$deref.invoke(core.clj:2207)
        at ccw_plugin_manager$create_user_plugin.invoke(ccw-plugin-manager.clj:48)
        at ccw_plugin_manager$__create_user_plugin_cmd_handler$fn__94.invoke(ccw-plugin-manager.clj:73)
        at ccw_plugin_manager$__create_user_plugin_cmd_handler.invoke(ccw-plugin-manager.clj:72)
        at clojure.lang.Var.invoke(Var.java:379)
        at ccw.util.GenericHandler$1.run(GenericHandler.java:52)
        at ccw.util.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:107)
        ... 61 more
```

**Comment by laurentpetit** [comment]
right, I changed the type of the return value and probably forgot to propagate to the plugin. Thanks for the report !
Fixed in ccw-plugin-manager. Fix will be included in the next release. It's a one-char fix tho, so you can probably try to apply it on your working system until the release comes out (probably this week).

Here's the commit: https://github.com/ccw-ide/ccw-plugin-manager/commit/f0f10fff47f321b774506abe0a6cecd710b7f9ea
